name: CI

on:
  push:
    branches-ignore:
      - main

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./devops/scripts/lint.ps1
        shell: pwsh

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./devops/scripts/build.ps1
        shell: pwsh
